# Generated by Django 4.2.6 on 2023-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipo', models.CharField(max_length=40)),
                ('ano_camiseta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Copas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copa', models.CharField(max_length=40)),
                ('num_copa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
